[#16] Temporary disable Java 10 build in master
Due to TLS error on package upload:
SunCertPathBuilderException: unable to find valid certification path to requested target
https://travis-ci.org/szpak/mockito-java8/jobs/354680524